
INSERT INTO `EON`.`USERS` (USER_NAME, USER_PASSWORD, USER_EMAIL) VALUES ("administrator", CONCAT("P", SHA1("administrator")), "administrator@eon.hr");
INSERT INTO `EON`.`USERS` (USER_NAME, USER_PASSWORD, USER_EMAIL) VALUES ("Ovca", CONCAT("P", SHA1("rootpass")), "administrator@eon.hr");
INSERT INTO `EON`.`USERS` (USER_NAME, USER_PASSWORD, USER_EMAIL) VALUES ("Pero", CONCAT("P", SHA1("pero")), "administrator@eon.hr");
INSERT INTO `EON`.`USERS` (USER_NAME, USER_PASSWORD, USER_EMAIL) VALUES ("Pavo", CONCAT("P", SHA1("pavo")), "administrator@eon.hr");

INSERT INTO `EON`.`ROOMS` (ROOM_NAME, ROOM_CAPACITY) VALUES ("DEV ROOM", 16);
INSERT INTO `EON`.`ROOMS` (ROOM_NAME, ROOM_CAPACITY) VALUES ("PUBLIC ROOM", 5);
INSERT INTO `EON`.`ROOMS` (ROOM_NAME, ROOM_CAPACITY) VALUES ("PRIVATE ROOM", 2);

